### ISSUE TITLE
NeosVR Token expired after a while

### ISSUE THREAD

**Issue by brodokk** [Resonite-Community-Projects/community_events.resonite#5]
```
bots_1   | ERROR:apscheduler.executors.default:Job "NeosVRCalendarTransmitter.transmitt (trigger: interval[0:01:00], next run at: 2023-05-20 08:28:40 UTC)" raised an exception
bots_1   | Traceback (most recent call last):
bots_1   |   File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
bots_1   |     retval = job.func(*job.args, **job.kwargs)
bots_1   |   File "/app/EventsTransmitters/NeosVRCalendarTransmitter.py", line 102, in transmitt
bots_1   |     setCloudVar = self.nclient.setCloudVar(
bots_1   |   File "/usr/local/lib/python3.10/site-packages/neosvrpy/client.py", line 328, in setCloudVar
bots_1   |     return self._request(
bots_1   |   File "/usr/local/lib/python3.10/site-packages/neosvrpy/client.py", line 111, in _request
bots_1   |     raise neos_exceptions.InvalidToken("Token expired")
bots_1   | neosvrpy.exceptions.InvalidToken: Token expired
```

**Comment by brodokk** [comment]
This should be solved with the temporary fixed by this two commits https://github.com/brodokk/neosvrpy/commit/80f7c20f0310cbbbcecf78e3df1afe475131d3a4 and https://github.com/brodokk/neosvrpy/commit/8a2922f0fbe63250c357752612d33eda749ca4cb

**Comment by brodokk** [comment]
I don't see this happening anymore, I'm closing
